#Introduction to NumPy
1. What is NumPy?
NumPy (Numerical Python) is an open-source Python library for:

Handling multi-dimensional arrays (ndarray)

Performing fast mathematical and statistical operations

Supporting linear algebra, Fourier transforms, and random number generation

It’s the core numerical computing tool in Python, forming the base for libraries like Pandas, SciPy, scikit-learn, TensorFlow, and more.

2. Features of NumPy
N-dimensional array object (ndarray) for storing homogeneous data

Vectorized operations (no explicit loops needed)

Broadcasting → Operations on arrays of different shapes

Rich mathematical functions → trigonometry, statistics, linear algebra

Interoperability → Works with C/C++ and Fortran

Efficient memory usage → Stores data in contiguous memory blocks

3. Why NumPy is Fast
Written in C → Avoids Python’s interpreter overhead

Vectorization → Executes operations on entire arrays at once

Contiguous Memory Layout → Enables CPU cache optimization

Low-level optimizations → Uses BLAS, LAPACK, or Intel MKL libraries

Applications

Data Analysis → Base for Pandas

Machine Learning → Used in TensorFlow, PyTorch

Scientific Computing → Physics, statistics, simulations

Image Processing → Images as arrays

| Aspect          | Python List                   | NumPy Array                    |
| --------------- | ----------------------------- | ------------------------------ |
| **Data Type**   | Can hold mixed types          | Homogeneous (single data type) |
| **Speed**       | Slow for numerical operations | Very fast (C-level operations) |
| **Memory**      | Uses more memory              | More memory-efficient          |
| **Operations**  | No vectorized math            | Supports vectorized math       |
| **Performance** | Loops in Python               | Loops in compiled C code       |


In [1]:
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Mathematical operations
print(arr * 2)  # [ 2  4  6  8 10]
print(arr + 3)  # [ 4  5  6  7  8]


[ 2  4  6  8 10]
[4 5 6 7 8]


In [2]:
import numpy as np

# Python list
lst = [1, 2, 3, 4, 5]
# NumPy array
arr = np.array([1, 2, 3, 4, 5])

print([x*2 for x in lst])  # Python loop → [2, 4, 6, 8, 10]
print(arr * 2)             # Vectorized → [ 2  4  6  8 10]


[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


Installation

To install NumPy, run in your terminal or command prompt:

In [3]:
pip install numpy


Importing NumPy

It’s standard practice to import NumPy using the alias np:

In [4]:
import numpy as np


Using np makes code shorter and more readable.

Example: np.array() instead of numpy.array().

Checking NumPy Version

You can check the installed version with:

In [5]:
import numpy as np
print(np.__version__)


2.0.2


#Numpy Arrays

Creating Arrays from Python Lists

You can convert a normal Python list into a NumPy array using np.array().

In [6]:
import numpy as np

# Python list
py_list = [1, 2, 3, 4, 5]

# Convert to NumPy array
arr = np.array(py_list)

print(arr)          # [1 2 3 4 5]
print(type(arr))    # <class 'numpy.ndarray'>


[1 2 3 4 5]
<class 'numpy.ndarray'>


Specifying Data Type with dtype

You can set the data type of the array explicitly using dtype.



In [7]:
# Integer array
arr_int = np.array([1, 2, 3], dtype=int)
print(arr_int, arr_int.dtype)  # [1 2 3] int64

# Float array
arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float, arr_float.dtype)  # [1. 2. 3.] float64

# Complex numbers
arr_complex = np.array([1, 2, 3], dtype=complex)
print(arr_complex, arr_complex.dtype)  # [1.+0.j 2.+0.j 3.+0.j]

# Strings
arr_str = np.array([1, 2, 3], dtype=str)
print(arr_str, arr_str.dtype)  # ['1' '2' '3'] <U1


[1 2 3] int64
[1. 2. 3.] float64
[1.+0.j 2.+0.j 3.+0.j] complex128
['1' '2' '3'] <U1


#NumPy Array Types
NumPy arrays can have any number of dimensions (also called rank).
The ndim attribute tells you how many dimensions an array has.

| Type | Example Shape | Real-world Example                  |
| ---- | ------------- | ----------------------------------- |
| 1D   | (5,)          | Temperature readings in a week      |
| 2D   | (3, 4)        | Spreadsheet data (rows × columns)   |
| 3D   | (10, 28, 28)  | 10 grayscale images of 28×28 pixels |
| n-D  | varies        | Deep learning tensors               |


1D Array (One-Dimensional)
A simple list of elements.

In [8]:
import numpy as np

arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)
print("Dimensions:", arr1D.ndim)   # 1
print("Shape:", arr1D.shape)       # (5,)


[1 2 3 4 5]
Dimensions: 1
Shape: (5,)


2D Array (Two-Dimensional)

Like a matrix — rows and columns.

In [9]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)
print("Dimensions:", arr2D.ndim)   # 2
print("Shape:", arr2D.shape)       # (2, 3)


[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)


3D Array (Three-Dimensional)

Like a cube of numbers — depth × rows × columns.

In [10]:
arr3D = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3D)
print("Dimensions:", arr3D.ndim)   # 3
print("Shape:", arr3D.shape)       # (2, 2, 2)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


N-Dimensional Arrays


You can have arrays with 4D, 5D, or more dimensions.

In [11]:
arrND = np.array([1, 2, 3], ndmin=5)
print(arrND)
print("Dimensions:", arrND.ndim)   # 5
print("Shape:", arrND.shape)       # (1, 1, 1, 1, 3)


[[[[[1 2 3]]]]]
Dimensions: 5
Shape: (1, 1, 1, 1, 3)


#Array Attributes in NumPy
NumPy arrays (ndarray) come with several built-in attributes that give information about their shape, size, dimensions, data type, and memory layout.

Let’s explore the most common ones.



| Attribute   | Meaning               | Example        |
| ----------- | --------------------- | -------------- |
| `.ndim`     | Number of dimensions  | `2`            |
| `.shape`    | Size along each axis  | `(2, 3)`       |
| `.size`     | Total elements        | `6`            |
| `.dtype`    | Data type of elements | `int64`        |
| `.itemsize` | Bytes per element     | `8`            |
| `.nbytes`   | Total memory usage    | `48`           |
| `.T`        | Transpose of array    | Matrix flipped |


.ndim — Number of Dimensions

In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)   # 2


2


.shape — Shape of Array

In [13]:
print(arr.shape)  # (2, 3)


(2, 3)


 .size — Total Number of Elements

In [14]:
print(arr.size)   # 6


6


 .dtype — Data Type of Elements

In [15]:
print(arr.dtype)  # int64 (depends on system)


int64


.itemsize — Size of Each Element (Bytes)

In [16]:
print(arr.itemsize)  # 8 (for int64, 8 bytes per element)


8


.nbytes — Total Bytes Consumed

In [17]:
print(arr.nbytes)  # size × itemsize = 6 × 8 = 48


48


.T — Transpose of Array

In [18]:
print(arr.T)
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


#Type Conversion in NumPy
Type conversion means changing the data type (dtype) of a NumPy array.
NumPy provides two main ways to do this:

Using astype() Method

The astype() method creates a new array with the desired data type.

In [19]:
import numpy as np

arr = np.array([1.2, 3.4, 5.6])
print(arr, arr.dtype)   # [1.2 3.4 5.6] float64

# Convert to integer
arr_int = arr.astype(int)
print(arr_int, arr_int.dtype)  # [1 3 5] int64

# Convert to string
arr_str = arr.astype(str)
print(arr_str, arr_str.dtype)  # ['1.2' '3.4' '5.6'] <U32


[1.2 3.4 5.6] float64
[1 3 5] int64
['1.2' '3.4' '5.6'] <U32


Changing dtype During Array Creation

You can specify the data type when creating the array.

In [20]:
arr2 = np.array([1, 2, 3], dtype=float)
print(arr2, arr2.dtype)  # [1. 2. 3.] float64


[1. 2. 3.] float64


Common Data Types in NumPy

| Data Type   | Description                |
| ----------- | -------------------------- |
| `int8`      | Integer (1 byte)           |
| `int32`     | Integer (4 bytes)          |
| `int64`     | Integer (8 bytes)          |
| `float32`   | Float (4 bytes)            |
| `float64`   | Float (8 bytes, default)   |
| `complex64` | Complex number (2×float32) |
| `bool`      | Boolean (`True`/`False`)   |
| `str`       | String (Unicode)           |


Memory Optimization

If you have large datasets, you can reduce memory usage by converting types.

In [21]:
big_arr = np.array([1000, 2000, 3000], dtype=np.int64)
print(big_arr.nbytes)  # 24 bytes

small_arr = big_arr.astype(np.int16)
print(small_arr.nbytes)  # 6 bytes


24
6


#Array Indexing
Indexing means accessing specific elements in a NumPy array.

1D Array Indexing

In [22]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element → 10
print(arr[-1])  # Last element → 50
print(arr[2])   # Third element → 30


10
50
30


2D Array Indexing

Use row index and column index.

In [23]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(arr2D[0, 0])  # 1 (row 0, col 0)
print(arr2D[1, 2])  # 6 (row 1, col 2)
print(arr2D[-1, -1])# 6 (last row, last col)


1
6
6


3D Array Indexing

In [24]:
arr3D = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(arr3D[0, 1, 1])  # 4 (block 0, row 1, col 1)
print(arr3D[1, 0, 0])  # 5


4
5


Negative Indexing

Negative indices count from the end of the array.

In [28]:
print(arr[-1])   # Last element → 50
print(arr[-2])   # Second last → 40

print(arr2D[-1, -1])  # Last row, last column → 6
print(arr2D[-2, -3])  # First row, first column → 1


50
40
9
4


2. Array Slicing

Slicing lets you extract a range of elements using:

| Operation    | Example         | Meaning                    |
| ------------ | --------------- | -------------------------- |
| Index single | `arr[2]`        | Element at index 2         |
| Index 2D     | `arr[1, 2]`     | Row 1, col 2               |
| Slice 1D     | `arr[1:4]`      | Elements from index 1 to 3 |
| Slice 2D     | `arr[0:2, 1:3]` | Rows 0–1, cols 1–2         |
| Step slicing | `arr[::2]`      | Every 2nd element          |
| Reverse      | `arr[::-1]`     | Reverse order              |


| Feature           | Example             | Result           |
| ----------------- | ------------------- | ---------------- |
| 1D indexing       | `arr[2]`            | 30               |
| 2D indexing       | `arr2D[1, 2]`       | 6                |
| Negative indexing | `arr[-1]`           | 50               |
| Step slicing 1D   | `arr[::2]`          | \[10 30 50]      |
| Step slicing 2D   | `arr2D[::-1, ::-1]` | Reverse 2D array |


[start : stop : step]


start → Starting index (inclusive)

stop → Ending index (exclusive)

step → Interval between elements

1D Array Slicing

In [25]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[::2])    # [10 30 50]
print(arr[::-1])   # [50 40 30 20 10] (reversed)


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [29]:
print(arr[1:5:2])  # [20 40] → from index 1 to 4, step 2
print(arr[::2])    # [10 30 50] → every 2nd element
print(arr[::-1])   # [50 40 30 20 10] → reverse


[20 40]
[10 30 50]
[50 40 30 20 10]


2D Array Slicing

In [26]:
arr2D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2D[0:2, 1:3])  # [[2 3]
                        #  [5 6]]
print(arr2D[:, 0])      # [1 4 7] → all rows, col 0
print(arr2D[1, :])      # [4 5 6] → row 1, all columns


[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


In [30]:
print(arr2D[::2, ::2])
# Every 2nd row, every 2nd column
# [[1 3]]

print(arr2D[::-1, ::-1])
# Reverse rows & columns
# [[6 5 4]
#  [3 2 1]]


[[1 3]
 [7 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


3D Array Slicing

In [27]:
arr3D = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(arr3D[:, :, 1])  # All blocks, all rows, col 1 → [[2 4]
                       #                               [6 8]]


[[2 4]
 [6 8]]


#Copy vs View

| Method    | Shares Data? | Memory Usage | Changes Affect Original? |
| --------- | ------------ | ------------ | ------------------------ |
| `.copy()` | ❌ No         | More         | ❌ No                     |
| `.view()` | ✅ Yes        | Less         | ✅ Yes                    |


What’s the Difference?

When you create a copy of an array, NumPy makes a completely new array in memory.
When you create a view, NumPy creates a new object that refers to the same data in memory.



.copy() — Creates an Independent Array

Data is fully duplicated into a new memory location.

Changes in the copy do not affect the original.

In [31]:
import numpy as np

arr = np.array([1, 2, 3])
copy_arr = arr.copy()

copy_arr[0] = 99

print("Original:", arr)     # [1 2 3]
print("Copy:", copy_arr)    # [99  2  3]


Original: [1 2 3]
Copy: [99  2  3]


.view() — Shares the Same Data

Creates a new array object pointing to the same memory.

Changes in one affect the other.

In [32]:
arr = np.array([1, 2, 3])
view_arr = arr.view()

view_arr[0] = 99

print("Original:", arr)     # [99  2  3]
print("View:", view_arr)    # [99  2  3]


Original: [99  2  3]
View: [99  2  3]


Check Memory Sharing

NumPy provides .base to see if arrays share the same data:

python
Copy code


In [33]:
print(copy_arr.base)  # None → independent
print(view_arr.base)  # [99  2  3] → shares data with arr


None
[99  2  3]


#Predefined Arrays in NumPy
NumPy has built-in functions to create arrays with preset values without manually specifying each element.

| Function     | Purpose                       |
| ------------ | ----------------------------- |
| `np.zeros()` | All zeros                     |
| `np.ones()`  | All ones                      |
| `np.full()`  | All elements with given value |
| `np.eye()`   | Identity matrix               |
| `np.empty()` | Uninitialized array           |


np.zeros() – Array of Zeros

Creates an array filled with 0.

In [34]:
import numpy as np

zeros_arr = np.zeros((3, 4))
print(zeros_arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.ones() – Array of Ones

Creates an array filled with 1.



In [35]:
ones_arr = np.ones((2, 3), dtype=int)
print(ones_arr)


[[1 1 1]
 [1 1 1]]


np.full() – Array with Custom Value

Creates an array filled with a specified number.


In [36]:
full_arr = np.full((3, 3), 7)
print(full_arr)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


np.eye() – Identity Matrix

Square matrix with 1’s on diagonal, 0’s elsewhere.

In [37]:
identity_arr = np.eye(4)
print(identity_arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


np.empty() – Uninitialized Array

Creates an array without setting values (contains random garbage values from memory).

In [38]:
empty_arr = np.empty((2, 3))
print(empty_arr)


[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


#Range & Sequence Arrays

np.arange() – Range with Step

Works like Python’s range(), but returns a NumPy array.

| Function        | Purpose                              | Example Output    |
| --------------- | ------------------------------------ | ----------------- |
| `np.arange()`   | Sequence with fixed step             | `[0, 2, 4, 6]`    |
| `np.linspace()` | Fixed number of evenly spaced values | `[0, 0.25, 0.5]`  |
| `np.logspace()` | Even spacing on logarithmic scale    | `[10, 100, 1000]` |


In [39]:
import numpy as np

arr1 = np.arange(0, 10, 2)  # start=0, stop=10, step=2
print(arr1)  # [0 2 4 6 8]

arr2 = np.arange(5)  # Only stop value
print(arr2)  # [0 1 2 3 4]


[0 2 4 6 8]
[0 1 2 3 4]


np.linspace() – Evenly Spaced Numbers


Generates a fixed number of equally spaced values between start and stop (inclusive).

In [40]:
arr3 = np.linspace(0, 1, 5)  # start=0, stop=1, num=5
print(arr3)  # [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


np.logspace() – Logarithmic Scale

Generates values spaced evenly on a log scale (powers of 10 by default).

In [41]:
arr4 = np.logspace(1, 3, 4)  # 10^1 to 10^3, 4 values
print(arr4)  # [  10.  100.  1000. ]


[  10.           46.41588834  215.443469   1000.        ]


#Identity & Diagonal Matrices

np.eye() – Identity Matrix with Custom Offset

Creates a 2D array with 1s on the main diagonal and 0s elsewhere.

| Feature         | `np.eye()`          | `np.identity()`  |
| --------------- | ------------------- | ---------------- |
| Shape           | Can be rectangular  | Always square    |
| Offset diagonal | Yes (`k` parameter) | No               |
| Parameters      | `N, M, k`           | `n` (single int) |


In [42]:
import numpy as np

# 3x3 identity matrix
m1 = np.eye(3)
print(m1)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


You can shift the diagonal using k:

In [43]:
# Ones above the main diagonal
m2 = np.eye(4, k=1)
print(m2)


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


Parameters:

N → number of rows

M → number of columns (optional, default = N)

k → diagonal index (0 = main, 1 = above, -1 = below)

np.identity() – Always a Square Identity Matrix

Creates a square identity matrix (only one parameter: size).

In [44]:
m3 = np.identity(4)
print(m3)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Random Array

| Function             | Purpose                            | Range / Distribution |
| -------------------- | ---------------------------------- | -------------------- |
| `rand()`             | Uniform floats                     | \[0, 1)              |
| `randn()`            | Standard normal (Gaussian)         | (-∞, ∞)              |
| `randint(low, high)` | Random integers in given range     | \[low, high)         |
| `seed()`             | Fix randomness for reproducibility | N/A                  |


np.random.rand() – Uniform Distribution [0, 1)

Generates random numbers uniformly between 0 and 1.

In [45]:
import numpy as np

# Random float between 0 and 1
a = np.random.rand()
print(a)

# 1D array of 5 random numbers
b = np.random.rand(5)
print(b)

# 2D array (3 rows, 4 columns)
c = np.random.rand(3, 4)
print(c)


0.0005045531774415801
[0.94025161 0.3205117  0.22025355 0.7053402  0.71860552]
[[0.48287866 0.77779383 0.57266871 0.8512962 ]
 [0.62741365 0.36340803 0.14903961 0.51772598]
 [0.5557307  0.94063867 0.88552643 0.15457943]]


np.random.randn() – Standard Normal Distribution

Generates random numbers from a normal distribution (mean = 0, std = 1).

In [46]:
# Single random value
d = np.random.randn()
print(d)

# 1D array
e = np.random.randn(5)
print(e)

# 2D array
f = np.random.randn(3, 4)
print(f)


1.4732648222997538
[ 0.0707143   0.9567713  -0.31949807 -1.0500971   1.77247982]
[[-0.25749872  0.26722702  0.95502944 -0.40339661]
 [ 0.24241095  0.6428012  -0.71548493 -0.07099809]
 [-0.99851016  0.5099703   0.7825856  -1.76051474]]


np.random.randint() – Random Integers

Generates random integers in a given range.

In [47]:
# Single random integer between 1 and 10
g = np.random.randint(1, 10)
print(g)

# 1D array of integers
h = np.random.randint(1, 10, size=5)
print(h)

# 2D array
i = np.random.randint(1, 100, size=(3, 4))
print(i)


3
[7 7 1 3 6]
[[90 15 54 76]
 [21 34 34 77]
 [16 88 48  4]]


np.random.seed() – Reproducibility

Sets the seed so that random results can be reproduced.

In [48]:
np.random.seed(42)
print(np.random.rand(3))  # Same output every time

np.random.seed(42)
print(np.random.rand(3))  # Exactly same as above


[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


#Array Operations in NumPy

NumPy lets you perform vectorized operations directly on arrays without loops, which makes it faster and more concise than plain Python.


Element-wise Operations


NumPy performs operations element-by-element without loops.

In [50]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division
print(a % b)   # Modulus
print(a ** 2)  # Power


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[1 4 9]


***Broadcasting***



Broadcasting lets NumPy perform operations on arrays of different shapes by stretching the smaller one without copying data.

| Operation Type   | Examples                                |
| ---------------- | --------------------------------------- |
| **Element-wise** | `+`, `-`, `*`, `/`                      |
| **Broadcasting** | Different shapes, compatible via rules  |
| **Ufuncs**       | `np.add`, `np.sin`, `np.exp`            |
| **Aggregation**  | `np.sum`, `np.mean`, `np.max`, `np.min` |
| **Axis Control** | `axis=0` (columns), `axis=1` (rows)     |


***Rules***

Compare shapes from right to left.

Dimensions are compatible if:

They are equal, or

One of them is 1.

If incompatible → error.

In [51]:
a = np.array([[1], [2], [3]])   # Shape (3,1)
b = np.array([10, 20, 30])      # Shape (3,)
result = a + b                  # Shape → (3,3)
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


Universal Functions (ufuncs)

Arithmetic ufuncs

In [52]:
print(np.add(a, b))       # Same as a + b
print(np.subtract(a, b))  # Same as a - b
print(np.multiply(a, b))  # Same as a * b
print(np.divide(a, b))    # Same as a / b
print(np.power(a, 2))     # Same as a**2
print(np.mod(b, 3))       # Modulus


[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[ -9 -19 -29]
 [ -8 -18 -28]
 [ -7 -17 -27]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]
[[0.1        0.05       0.03333333]
 [0.2        0.1        0.06666667]
 [0.3        0.15       0.1       ]]
[[1]
 [4]
 [9]]
[1 2 0]


Trigonometric Functions

In [53]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Exponential & Logarithmic

In [54]:
nums = np.array([1, 2, 3])
print(np.exp(nums))        # e^x
print(np.log(nums))        # Natural log
print(np.log10(nums))      # Base-10 log


[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]


Aggregation Functions

In [55]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr))      # Sum of all elements → 21
print(np.mean(arr))     # Mean → 3.5
print(np.max(arr))      # Max → 6
print(np.min(arr))      # Min → 1
print(np.prod(arr))     # Product of all elements
print(np.std(arr))      # Standard deviation
print(np.var(arr))      # Variance


21
3.5
6
1
720
1.707825127659933
2.9166666666666665


Axis Parameter
axis=0 → Column-wise (down the rows)

axis=1 → Row-wise (across the columns)

In [56]:
print(np.sum(arr, axis=0))  # Column sums → [5 7 9]
print(np.sum(arr, axis=1))  # Row sums → [ 6 15]


[5 7 9]
[ 6 15]


#Advanced Indexing & Slicing in NumPy

| Feature              | Description                   | Example               |
| -------------------- | ----------------------------- | --------------------- |
| **Boolean Indexing** | Select with conditions        | `arr[arr > 5]`        |
| **Fancy Indexing**   | Select with integer lists     | `arr[[0,2,4]]`        |
| **Masking**          | Boolean mask array            | `arr[mask]`           |
| **`np.where()`**     | Indices / conditional replace | `np.where(arr>5,1,0)` |
| **`np.nonzero()`**   | Non-zero indices              | `np.nonzero(arr)`     |
| **Ellipsis**         | Full slices in remaining dims | `arr[...,2]`          |
| **`np.newaxis`**     | Add new dimension             | `arr[:,np.newaxis]`   |


***Boolean Indexing***

Select elements based on True/False conditions.

In [57]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Condition → Boolean array
mask = arr > 25
print(mask)         # [False False  True  True  True]

# Use mask to filter
print(arr[mask])    # [30 40 50]

# Directly inline
print(arr[arr % 20 == 0])  # [20 40]


[False False  True  True  True]
[30 40 50]
[20 40]


**Fancy Indexing**

Select elements using integer arrays or lists.

In [58]:
arr = np.array([10, 20, 30, 40, 50])

# Select by positions
print(arr[[0, 2, 4]])   # [10 30 50]

# 2D example
mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat[[0, 2], [1, 0]])  # Picks (0,1) and (2,0) → [2, 5]


[10 30 50]
[2 5]


**Masking**

Mask = Boolean array used for selection.

In [59]:
arr = np.arange(10)
mask = arr % 2 == 0   # Even numbers
print(mask)           # [ True False True False True False True False True False]
print(arr[mask])      # [0 2 4 6 8]



[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


np.where()

Returns indices or values based on condition.

In [60]:
arr = np.array([10, 20, 30, 40])

# Get indices where condition is True
print(np.where(arr > 25))  # (array([2, 3]),)

# Replace values based on condition
print(np.where(arr > 25, arr, -1))
# [-1 -1 30 40]


(array([2, 3]),)
[-1 -1 30 40]


np.nonzero()

Find indices of non-zero (or True) elements.

In [61]:
arr = np.array([0, 3, 0, 4])
print(np.nonzero(arr))   # (array([1, 3]),)


(array([1, 3]),)


Indexing Tricks

Ellipsis (...)

Represents full slices across remaining dimensions.

In [62]:
arr = np.arange(27).reshape(3, 3, 3)
print(arr[1, ...])      # All rows & cols from 2nd block
print(arr[..., 2])      # Last column from all dimensions


[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


New axis (np.newaxis)

Adds an extra dimension.

In [63]:
arr = np.array([1, 2, 3])
print(arr.shape)        # (3,)

# Add new axis → column vector
col_vec = arr[:, np.newaxis]
print(col_vec.shape)    # (3,1)

# Add new axis → row vector
row_vec = arr[np.newaxis, :]
print(row_vec.shape)    # (1,3)


(3,)
(3, 1)
(1, 3)


#Shape Manipulation – NumPy



| Function           | Purpose              | New Axis? | View/Copy        |
| ------------------ | -------------------- | --------- | ---------------- |
| `.reshape()`       | Change shape         | No        | View if possible |
| `.ravel()`         | Flatten              | No        | View if possible |
| `.flatten()`       | Flatten              | No        | Copy             |
| `.T`               | Transpose            | No        | View             |
| `np.transpose()`   | Reorder axes         | No        | View             |
| `np.swapaxes()`    | Swap 2 axes          | No        | View             |
| `np.concatenate()` | Join arrays          | No        | —                |
| `np.hstack()`      | Stack horizontally   | No        | —                |
| `np.vstack()`      | Stack vertically     | No        | —                |
| `np.split()`       | Equal split          | —         | —                |
| `np.array_split()` | Unequal split        | —         | —                |
| `np.stack()`       | Stack along new axis | Yes       | Copy             |
| `np.dstack()`      | Stack along depth    | Yes       | Copy             |


Reshaping Arrays

.reshape() – Change the shape without changing data.

In [64]:
import numpy as np

arr = np.arange(6)  # [0 1 2 3 4 5]
reshaped = arr.reshape(2, 3)
print(reshaped)
# [[0 1 2]
#  [3 4 5]]


[[0 1 2]
 [3 4 5]]


.ravel() – Flatten to 1D, returns view (changes affect original if possible).

In [65]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.ravel()
flat[0] = 99
print(arr)  # [[99  2]
            #  [ 3  4]]


[[99  2]
 [ 3  4]]


.flatten() – Flatten to 1D, returns copy (independent of original).

In [66]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
flat[0] = 99
print(arr)  # [[1 2]
            #  [3 4]]


[[1 2]
 [3 4]]


Transpose & Axes Manipulation

.T – Simple transpose (swap rows & columns).

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


np.transpose() – Rearrange axes in any order.

In [68]:
arr = np.arange(8).reshape(2, 2, 2)
print(np.transpose(arr, (1, 0, 2)))  # Swap first two axes


[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


np.swapaxes() – Swap exactly two axes.

In [69]:
arr = np.arange(8).reshape(2, 2, 2)
print(np.swapaxes(arr, 0, 2).shape)  # (2, 2, 2)


(2, 2, 2)


Concatenation & Splitting

Concatenation

np.concatenate() – Join along an axis.

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
# [[1 2]
#  [3 4]
#  [5 6]]


[[1 2]
 [3 4]
 [5 6]]


np.hstack() – Horizontal stack (axis=1 for 2D).

np.vstack() – Vertical stack (axis=0 for 2D).

In [71]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.hstack((a, b)))  # [1 2 3 4]
print(np.vstack((a, b)))
# [[1 2]
#  [3 4]]


[1 2 3 4]
[[1 2]
 [3 4]]


Splitting

np.split() – Split into equal parts (must divide evenly).

In [72]:
arr = np.arange(6)
print(np.split(arr, 3))  # [array([0,1]), array([2,3]), array([4,5])]


[array([0, 1]), array([2, 3]), array([4, 5])]


np.array_split() – Split into uneven parts allowed.

In [73]:
arr = np.arange(7)
print(np.array_split(arr, 3))
# [array([0,1,2]), array([3,4]), array([5,6])]


[array([0, 1, 2]), array([3, 4]), array([5, 6])]


**Stacking**

np.stack() – Stack along a new axis.

In [74]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b), axis=0))
# [[1 2]
#  [3 4]]


[[1 2]
 [3 4]]


np.dstack() – Stack along depth (3rd axis).

In [75]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.dstack((a, b)))  # [[[1 3]
                          #   [2 4]]]


[[[1 3]
  [2 4]]]


#Linear Algebra with NumPy

NumPy provides powerful functions in the np.linalg module for matrix and linear algebra operations.



Dot Product & Matrix Multiplication

Element-wise multiplication

In [76]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A * B)  # Element-wise multiplication


[[ 5 12]
 [21 32]]


Matrix multiplication

In [77]:
print(np.dot(A, B))    # Dot product
print(A @ B)           # @ operator (same as dot)
print(np.matmul(A, B)) # Matrix multiplication


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Determinant & Inverse

In [78]:
det_A = np.linalg.det(A)   # Determinant
print(det_A)

inv_A = np.linalg.inv(A)   # Inverse matrix
print(inv_A)


-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


Eigenvalues & Eigenvectors

In [79]:
eig_vals, eig_vecs = np.linalg.eig(A)

print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Norms & Ranks

In [80]:
print(np.linalg.norm(A))           # Frobenius norm (default)
print(np.linalg.norm(A, ord=1))    # L1 norm
print(np.linalg.norm(A, ord=2))    # L2 norm

print(np.linalg.matrix_rank(A))    # Rank of matrix


5.477225575051661
6.0
5.464985704219043
2


Solving Linear Systems

Solve the system Ax = b:

In [81]:
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print(x)  # Solution vector


[1. 2.]


#Additional & Advanced NumPy Topics

NumPy Data Types

NumPy arrays have a single data type (dtype) for all elements.

In [82]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)  # int32

arr_float = np.array([1, 2, 3], dtype=np.float64)
print(arr_float.dtype)  # float64

arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.dtype)  # complex128


int32
float64
complex128


Vectorization vs Loops

NumPy is much faster than Python loops because operations are done in C internally.

In [83]:
import time

size = 10_000_000
x = np.arange(size)
y = np.arange(size)

# Vectorized
start = time.time()
z = x + y
print("Vectorized:", time.time() - start)

# Loop
x_list = list(range(size))
y_list = list(range(size))
start = time.time()
z_list = [x_list[i] + y_list[i] for i in range(size)]
print("Loop:", time.time() - start)


Vectorized: 0.04573178291320801
Loop: 1.291029453277588


Memory Layout

NumPy stores data in C-order (row-major) or Fortran-order (column-major).

In [84]:
arr_c = np.array([[1, 2], [3, 4]], order='C')
arr_f = np.array([[1, 2], [3, 4]], order='F')

print(arr_c.flags)
print(arr_f.flags)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Sorting & Searching

In [85]:
arr = np.array([3, 1, 2])
print(np.sort(arr))  # Sorted array
print(np.argsort(arr))  # Indices for sorting

sorted_idx = np.argsort(arr)
print(arr[sorted_idx])

print(np.searchsorted([1, 3, 5], 4))  # Index to insert 4


[1 2 3]
[1 2 0]
[1 2 3]
2


Set Operations

In [86]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.unique(a))
print(np.union1d(a, b))
print(np.intersect1d(a, b))
print(np.setdiff1d(a, b))


[1 2 3 4]
[1 2 3 4 5 6]
[3 4]
[1 2]


Random Module – More Control

In [87]:
# Random choice with/without replacement
print(np.random.choice([1, 2, 3, 4], size=2, replace=False))

# Shuffle array in-place
arr = np.arange(5)
np.random.shuffle(arr)
print(arr)


[2 3]
[4 0 3 2 1]


Mathematical Statistics

In [88]:
data = np.array([1, 2, 3, 4, 5])

print(np.median(data))
print(np.percentile(data, 50))  # same as median
print(np.percentile(data, [25, 75]))  # quartiles

hist, bins = np.histogram(data, bins=3)
print(hist)
print(bins)


3.0
3.0
[2. 4.]
[2 1 2]
[1.         2.33333333 3.66666667 5.        ]


Handling Missing Data

In [89]:
arr = np.array([1, np.nan, 3, np.nan])

print(np.isnan(arr))  # Boolean mask
print(np.nan_to_num(arr, nan=0))  # Replace NaN with 0


[False  True False  True]
[1. 0. 3. 0.]
